export const defaultRoute = {
  homepage: "/",
  product: "/products",
  productCategory: "/products/:name",
  productDetail: "/products/:category/:id",
  cart: "/cart",
  bill: "/bill",
  chat: "/chat",
  notification: "/notification",
  contact: "/contact",
  dashboard: "/admin",
  productManagement: "/admin/product",
  productDetailManagement: "/admin/product/:_id",
  newProduct: "/admin/product/new",
  categoryManagement: "/admin/category",
  viewCategory: "/admin/category/:_id",
  newCategory: "/admin/category/new",
  userManagement: "/admin/user",
  discountManagement: "/admin/discount",
  newDiscount: "/admin/discount/new",
  billManagement: "/admin/bill",
  saleDashboard: "/sale",
  saleFollower: "/sale/follower",
};
